version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/wdbml:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=wdbml-mysql-app
      - MYSQL_USER=wdbmluser
      - MYSQL_PASSWORD=wdbmlpass
      - MYSQL_DB=wdbml_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "30001:80"
    container_name: wdbml-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=wdbmluser
      - MYSQL_PASSWORD=wdbmlpass
      - MYSQL_DATABASE=wdbml_db
    container_name: wdbml-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=wdbml-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: wdbml-phpmyadmin-app
networks:
  frontend:
  backend: